export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'


export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL'


export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST'
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS'
export const GET_POST_BY_ID_FAIL = 'GET_POST_BY_ID_FAIL'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'


export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL'


export const DISLIKE_POST_REQUEST = 'DISLIKE_POST_REQUEST'
export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS'
export const DISLIKE_POST_FAIL = 'DISLIKE_POST_FAIL'


export const COMMENT_REQUEST = 'COMMENT_REQUEST'
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_FAIL = 'COMMENT_FAIL'


export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'