export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST'
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL'

export const GET_MY_PROFILE_REQUEST = 'GET_MY_PROFILE_REQUEST'
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS'
export const GET_MY_PROFILE_FAIL = 'GET_MY_PROFILE_FAIL'



export const GET_ALL_PROFILES_REQUEST = 'GET_ALL_PROFILES_REQUEST'
export const GET_ALL_PROFILES_SUCCESS = 'GET_ALL_PROFILES_SUCCESS'
export const GET_ALL_PROFILES_FAIL = 'GET_ALL_PROFILES_FAIL'

export const PROFILE_BY_ID_REQUEST = 'PROFILE_BY_ID_REQUEST'
export const PROFILE_BY_ID_SUCCESS = 'PROFILE_BY_ID_SUCCESS'
export const PROFILE_BY_ID_FAIL = 'PROFILE_BY_ID_FAIL'


export const DELETE_PROFILE_REQUEST = 'DELETE_PROFILE_REQUEST'
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS'
export const DELETE_PROFILE_FAIL = 'DELETE_PROFILE_FAIL'

